### ISSUE TITLE
Featured project photo is missing 

### ISSUE THREAD

**Issue by Ewpratten** [frc5024/frc5024.github.io#2]
This happens when someone deletes an Instagram photo.. Can someone find a new photo of HATCHfield for the site? You basically just need to change the `featured_image` tag in `_config.yml`

**Comment by wm-c** [comment]
What type of image are we looking for, would this image be fine?

https://www.instagram.com/p/Bujf9tlFNsQ/media/?size=l

**Comment by Ewpratten** [comment]
That is a good image
